name: Daily Twitter Scheduler

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  run-and-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install python-dotenv playwright
        playwright install

    - name: Run scheduler script
      env:
        TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
        TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
      run: python runner.py

    - name: Configure Git and Push Login Data
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add login/default/login_data || true
        git diff --cached --quiet || git commit -m "Update Playwright login session data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
